title: Portfolio de Saddam
email: dev.hsaddam@gmail.com
description: >-
  
baseurl: ""
url: ""
github_username:  devsha256
linkedin_username: "hsaddam"
youtube_username: "@tea-verse"
resume_drive_link: "https://drive.google.com/file/d/17QT4UYfgNcnS8uLmO_vOnwcSDOq1QAWy/view?usp=sharing"

# Build settings
theme: minima
header_pages:
  - credentials/index.markdown
  - skills.markdown
  - projects.markdown
  - repos.markdown
  # - notice-period.markdown