title: Portfolio de Saddam
email: dev.hsaddam@gmail.com
description: >-
  
baseurl: ""
url: "https://devsha256.github.io"
github_username:  devsha256
linkedin_username: "hsaddam"

# Build settings
theme: minima