title: Portfolio de Saddam
email: dev.hsaddam@gmail.com
description: >-
  
baseurl: ""
url: ""
github_username:  devsha256
linkedin_username: "hsaddam"
youtube_username: "@tea-verse"

# Build settings
theme: minima
header_pages:
  - credentials/index.markdown
  - skills.markdown
  - projects.markdown
  - repos.markdown
  - notice-period.markdown